spring.application.name=rag-agents-app

openai.model=gpt-4o-mini
openai.api.key=your_openai_api_key_here
pgvector.host=localhost
pgvector.port=5433
pgvector.database=ragdb
pgvector.user=postgres
pgvector.password=postgres
pgvector.table=support_policies

##docker run -d --name pgvector -p 5433:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=ragdb pgvector/pgvector:pg16


