spring.application.name=langchain-rag
openai.model=gpt-4o-mini
openai.api.key=your_openai_api_key_here

rag.store=pgvector
#rag.store=memory
## use in terminal to run docker image
##docker run -d --name pgvector -p 5433:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=ragdb pgvector/pgvector:pg16

# PG vector config
rag.pgvector.host=localhost
rag.pgvector.port=5433
rag.pgvector.database=ragdb
rag.pgvector.user=postgres
rag.pgvector.password=postgres

# Name of the table where embeddings are stored.
rag.pgvector.table=embeddings


